# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH
- bash: conda create --yes --quiet --name myEnvironment
  displayName: Create Anaconda environment
- bash: |
    source activate myEnvironment
    pip install -r requirements.txt
    pytest
  displayName: pytest
# BUNDLE FUNCTION
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Build/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/output.zip'
    replaceExistingArchive: true
# DEPLOY FUNCTION
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'ExperimentnLearnNonProd(bc69d98c-7d2b-4542-88a4-f86eb4aea4a5)'
    appType: 'functionAppLinux'
    appName: 'brhung-deployment-test'
    package: '$(System.DefaultWorkingDirectory)/output.zip'