stages:
- stage: Deployment
  jobs:
  - job: 
    displayName: Deployment Job
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    # SET PYTHON VERSION
    - task: UsePythonVersion@0
      displayName: "Setting Required Python Version for Azure Functions"
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    # INIT CONDA ENVIRONMENT
    - bash: |
        python3.6 -m venv worker_venv
        source worker_venv/bin/activate
        pip3.6 install setuptools
        pip3.6 install -r requirements.txt
      displayName: Install Dependencies
    # BUNDLE FUNCTION
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(System.DefaultWorkingDirectory)/output.zip'
        replaceExistingArchive: true
    # DEPLOY FUNCTION
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'ExperimentnLearnNonProd(bc69d98c-7d2b-4542-88a4-f86eb4aea4a5)'
        appType: 'functionAppLinux'
        appName: 'brhung-deployment-test'
        package: '$(System.DefaultWorkingDirectory)/output.zip'
- stage: Validation
  dependsOn:
  - Deployment
  condition: succeeded('Deployment') 
  jobs:
  - job: 
    displayName: End-to-End Testing Job
    pool: server
    steps:
    # E2E TESTING
    - task: PublishToAzureServiceBus@1
      inputs:
        azureSubscription: 'test'
        messageBody: >
          {
            "name": "brhung-testing",
            "job": "!START",
            "auth_token": "$(system.AccessToken)",
            "build_id": "$(Build.BuildId)",
            "run_configuration": {
                "repository": "https://github.com/Mutilar/brhung-notebook/archive/master.zip",
                "conda_file": "environment.yml",
                "compute_target": "brhung-cpu",
                "notebooks": [                
                    "notebooks/00_quick_start/fastai_movielens.ipynb",
                    "notebooks/00_quick_start/lightgbm_tinycriteo.ipynb"
                ]
            },
            "azure_resources": {
                "organization": "t-brhung",
                "project": "brhung-test-pipeline",
                "run_id": "default_run_id",
                "service_principal": {
                    "username": "$(sp.client)",
                    "tenant": "$(sp.tenant)",
                    "password": "$(sp.password)"
                },
                "workspace": {
                    "name": "brhung-ml",
                    "subscription_id": "$(ws.subscription)",
                    "resource_group": "brhung-testing"
                }
            }
          }
        waitForCompletion: true # Allows for POST callback to close pipeline