# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# FORCE FUNCTION-COMPATIBLE PYTHON VERSION
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6.8'
    addToPath: true
    architecture: 'x64'
# UNIT-TESTING VIA CONDA ENVIRONMENT
- bash: |
    source activate myEnvironment
    pytest --junitxml=junit/unit-test.xml
  displayName: pytest
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'junit/*.xml'
  condition: succeededOrFailed()
# BUNDLE FUNCTION
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Build/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/output.zip'
    replaceExistingArchive: true
# DEPLOY FUNCTION
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'ExperimentnLearnNonProd(bc69d98c-7d2b-4542-88a4-f86eb4aea4a5)'
    appType: 'functionAppLinux'
    appName: 'brhung-deployment-test'
    package: '$(System.DefaultWorkingDirectory)/output.zip'