# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $(System.DefaultWorkingDirectory)!
  displayName: 'Run a one-line script'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Build/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/output.zip'
    replaceExistingArchive: true
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'ExperimentnLearnNonProd(bc69d98c-7d2b-4542-88a4-f86eb4aea4a5)'
    appType: 'functionAppLinux'
    appName: 'brhung-deployment-test'
    package: '$(System.DefaultWorkingDirectory)/*.zip'