stages:
- stage: Deployment
  jobs:
  - job: 
    displayName: Deployment Job
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    # SET PYTHON VERSION
    - task: UsePythonVersion@0
      displayName: "Setting Required Python Version for Azure Functions"
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    # INIT CONDA ENVIRONMENT
    - bash: |
        python3.6 -m venv worker_venv
        source worker_venv/bin/activate
        pip3.6 install setuptools
        pip3.6 install -r requirements.txt
      displayName: Install Dependencies
    # UNIT TESTING
    - bash: |
        source worker_venv/bin/activate
        pytest
      displayName: Run Unit Tests
    # BUNDLE FUNCTION
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(System.DefaultWorkingDirectory)/output.zip'
        replaceExistingArchive: true
    # DEPLOY FUNCTION
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: '$(fx.azureSubscription)'
        appType: 'functionAppLinux'
        appName: '$(fx.name)'
        package: '$(System.DefaultWorkingDirectory)/output.zip'
- stage: Validation
  dependsOn:
  - Deployment
  condition: succeeded('Deployment') 
  jobs:
  - job: 
    displayName: End-to-End Testing Job
    pool: server
    steps:
    # E2E TESTING
    - task: RunNotebookTest@1
      inputs:
        azureSubscription: 'test'
        waitForCompletion: true