name: environment
channels:
- defaults
dependencies:
- mock==2.0.0
- dask>=0.17.1
- fastparquet>=0.1.6
- gitpython>=2.1.8
- ipykernel>=4.6.1
- jupyter>=1.0.0
- matplotlib>=2.2.2
- numpy>=1.13.3
- pandas>=0.23.4
- pymongo>=3.6.1
- python==3.6.8
- pytest>=3.6.4
- numba>=0.38.1
- pip:
  - azureml-sdk[notebooks,tensorboard]==1.0.18
  - papermill==0.18.2
  - pandas
  - scikit-learn
  - sklearn