name: reco_gpu
channels:
- defaults
- conda-forge
- pytorch
- fastai
dependencies:
- mock==2.0.0
- dask>=0.17.1
- fastparquet>=0.1.6
- gitpython>=2.1.8
- ipykernel>=4.6.1
- jupyter>=1.0.0
- matplotlib>=2.2.2
- numpy>=1.13.3
- pandas>=0.23.4
- pymongo>=3.6.1
- python==3.6.8
- pytest>=3.6.4
- pytorch>=1.0.0
- seaborn>=0.8.1
- scikit-learn==0.19.1
- scipy>=1.0.0
- scikit-surprise>=1.0.6
- swig==3.0.12
- tensorflow-gpu==1.12.0
- lightgbm==2.2.1
- pyarrow>=0.8.0
- pyspark==2.3.1
- numba>=0.38.1
- pip:
  - azureml
  - azure-servicebus
  - azureml-sdk[notebooks,tensorboard]==1.0.18
  - azure-storage>=0.36.0
  - black>=18.6b4
  - category_encoders>=1.3.0
  - databricks-cli==0.8.6
  - dataclasses>=0.6
  - fastai==1.0.46
  - hyperopt==0.1.1
  - idna==2.7
  - memory-profiler>=0.54.0
  - nni==0.5.2.1.1
  - nvidia-ml-py3>=7.352.0
  - papermill==0.18.2
  - pydocumentdb>=2.3.3
  - tqdm==4.31.1
  - tensorflow==1.14.0
  - pymanopt